### ISSUE TITLE
implementation of fluctuation for observations

### ISSUE THREAD

**Issue by ebus-brgm** [apryet/adeqwat#17]
Hello fellow pymarthe devs;

There are a few issues with the add_fluc() function in class moptim:
1- for further use with PEST_HP (and corresponding observation group name length limitation of 12 characters); it would be extremely useful to replace the 'fluc' suffix addition to only 'f' for example; or parameterize the suffix name.

as a general example, in most France-located groundwater models, the observation name would be a standard BSS number:
e.g. mopt.add_obs(locnme='00238X0037') and consequently mopt.add_fluct(locnme='00238X0037', tag = 'm', on='mean) leads to an obs group name of '00238X0037mf' which fits nicely into 12 characters.

this would require modifying the add_fluc() function in moptim.py as well as the extract_prn() function in marthe_utils.pest_utils
(i can provide some suggested corrections)

2- the add_fluc() needs further parameters, including:

    some obs groups may contain 0-weight observations, and these 0-weight observation should also be 0-weight fluctuation

   the calculation of the fluctuation should encompass only the non-0 wie observations, otherwise the calculation is wrong

This would require modifying the add_fluc() function in moptim, for example carrying along the **kwargs option to use the weight; e.g. mopt.add_fluct(locnme='00238X0037', weight = wieght_list, tag = 'm', on='mean)
also the aggregation for the calculation should be restricted to non-0 obs, e.g. 

`                s = df.loc[df['weight'] != 0, 'value'].replace(self.nodata, pd.NA)  # replace nodata values by NaN and remove obs with 0 weight for fluct calculation
                sub_val = s.agg(on) if isinstance(on, str) else on
 `
here again I can suggest some modifications and pull requests

many thanks

**Comment by apryet** [comment]
Hello Etienne,
1. As far as I remember, observation may be 20-character long in PEST_HP. That being said, it is indeed more concise to keep only "f" of "fluc".
2. Good point !
You may push these updates !
Thank you,
Alexandre
