### ISSUE TITLE
:warning: `marthe_utils.set_tw()` not working

### ISSUE THREAD

**Issue by pmatran** [apryet/adeqwat#21]
Hi everyone :wave:,

I recently noticed that the functionality allowing you to control the model's **time window** was not working as expected on the **MONA** model. This is due to an incomplete _regex_ manipulation which does not match the target block in the `.mart` global parameters file, due to the inconsistency in blocks  headers  according to the  version of the **MARTHE** executable.

<br>

**What's wrong :grey_question:**

The current regex expression:

```python
r"\*{3}\s*Pas de Temps"
``` 
Target block header (**MONA**):

```latex
*** Pas et Sous-Pas de Temps                        ***
```
 
<br>

**Hint for solving the problem :bulb:**

I similar regex is already used in the `marthe_utils.get_tw()` including headers from previous **Marthe**versions. Why not just copy that one?

```python
r"\*{3}\s*(Pas|Pas de Temps) et"
``` 
<br>

:mag_right: Need to be tested carefully!

**Comment by apryet** [comment]
Great, thanks !
